### ISSUE TITLE
'valid' generation is checked, but model has dead features

### ISSUE THREAD

**Issue by cpwnd** [isa-group/BeTTy#3]
When I generate a feature model via https://betty.services.governify.io, I check the `Generate only valid models` und `Satisfiability`. The generated feature model contains dead features. Is this expected behaviour? Or can betty generate Feature models with constraints of moderat size (say >100 features and CTC < 50%) so that there are no dead features.

Great tool by the way! Thanks.

**Comment by ssegura** [comment]
Hi Chris,

Yes, it is the expected behaviour. A feature model is valid if it represents at least one valid product, which is compatible with the model having dead features. If you wish to avoid dead features I would recommend using an analyiss tool like FaMa (http://www.isa.us.es/fama/) to discard the models with dead features.

Sergio
